# Generated by Django 5.0.6 on 2024-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=200, verbose_name='Название курса')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Лекция')),
                ('content_lecture', models.TextField(max_length=1800, verbose_name='Текст')),
            ],
        ),
    ]
