# Generated by Django 5.0.6 on 2024-06-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_lecture_course_id_department_courses_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='name_course',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name_department',
            new_name='title',
        ),
    ]
