# Generated by Django 5.0.6 on 2024-06-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_name_course_courses_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='polls.department'),
            preserve_default=False,
        ),
    ]
