# Generated by Django 5.0.6 on 2024-06-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_courses_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='polls.department'),
        ),
    ]
